### ISSUE TITLE
Events page can be made better

### ISSUE THREAD

**Issue by drholmie** [MicrosoftMobileInnovationLab/Mlab_website_2.0#15]
### Feature Request
**Expected Improvement**:
The events page need not be made in such a constrained way as it currently as attached below.
The page can be made in a normal textual way, rather than forcing people to read into the tiny boxes. This would also allow more opportunities to expand on content, add images and better formatting.
 
![image](https://user-images.githubusercontent.com/19522710/64851153-71f47380-d634-11e9-8ab3-21840b6260cf.png)

**Comment by sumanthvrao** [comment]
@SparshTemani are you free to take take this up? no hurries, we can do this after ISA1 as well.

**Comment by SparshTemani** [comment]
I will take this task.
Will try to do it before CBT, if not will work on it as soon as CBTs are done.

**Comment by sumanthvrao** [comment]
Feature merged and deployed. @drholmie Check www.mlab.pes.edu.
